<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Template.Master" CodeBehind="ViewCart.aspx.vb" Inherits="OnlineStoreSummer2021.ViewCart" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:SqlDataSource ID="SqlDSCart" runat="server" 
        DataSourceMode="DataSet"
        ConnectionString="<%$ ConnectionStrings:ConnectionStringOnlineStore %>" 
        SelectCommand=""
        DeleteCommand="DELETE FROM [Cart] WHERE ([CartNo] = @CartNo AND [ProductID] = @ProductID)"
        UpdateCommand="UPDATE [Cart] SET [Quantity] = @Quantity WHERE ([CartNo] = @CartNo AND [ProductID] = @ProductID)">
    </asp:SqlDataSource>
    <asp:GridView ID="gvCart" runat="server" AutoGenerateColumns="False" 
        DataSourceID="SqlDSCart" AllowPaging="True" PageSize="3" DataKeyNames="CartNo,ProductID"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        EmptyDataText="There are no product in the cart.">
        <Columns>
            <asp:BoundField DataField="ProductID" HeaderText="Product ID" InsertVisible="False" ReadOnly="true"
                SortExpression="ProductID" />
            <asp:BoundField DataField="ProductName" HeaderText="Product Name" InsertVisible="False" ReadOnly="true"
                SortExpression="ProductName" />
            <asp:BoundField DataField="Quantity" HeaderText="Quantity" 
                SortExpression="Quantity" />
            <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" InsertVisible="False" ReadOnly="true" />
        </Columns>
    </asp:GridView>
	
	<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="cart_product">
                                <asp:Image ID="imgProduct" runat="server" /> <!-- Image -->
								<a href="#"><img src="images/cart/one.png" alt=""></a>
							</td>
							<td class="cart_description">
                                <asp:Label ID="lblDescription" runat="server" Text=""></asp:Label> <!-- Description -->
								<h4><a href="#">Colorblock Scuba</a></h4>
								<p>Web ID: 1089772</p>
							</td>
							<td class="cart_price">
                                <asp:Label ID="lblPrice" runat="server" Text="Label"></asp:Label> <!-- Price -->
								<p>$59</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
                                    <asp:Button ID="Button1" runat="server" Text="Button" /> <!-- Qty button UP -->
									<a class="cart_quantity_up" href="#"> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
									<asp:TextBox ID="TextBox1" runat="server"></asp:TextBox> <!-- Qty -->
									<asp:Button ID="Button2" runat="server" Text="Button" /> <!-- Qty button DOWN -->
									<a class="cart_quantity_down" href="#"> - </a>
								</div>
							</td>
							<td class="cart_total">
                                <asp:Label ID="lblTotal" runat="server" Text="Label"></asp:Label> <!-- Total price -->
								<p class="cart_total_price">$59</p>
							</td>
							<td class="cart_delete">
                                <asp:Button ID="Button3" runat="server" Text="Button" /> <!-- Delete button -->
								<a class="cart_quantity_delete" href="#"><i class="fa fa-times"></i></a>
							</td>
						</tr>
						<%--<tr>

							<td class="cart_product">
								<a href=""><img src="images/cart/three.png" alt=""></a>
							</td>
							<td class="cart_description">
								<h4><a href="">Colorblock Scuba</a></h4>
								<p>Web ID: 1089772</p>
							</td>
							<td class="cart_price">
								<p>$59</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href=""> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
									<a class="cart_quantity_down" href=""> - </a>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price">$59</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
							</td>
						</tr>--%>
					</tbody>
				</table>
			</div>
</asp:Content>
